name: GitHub Context

on:
  workflow_dispatch:

jobs:
  show-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info about GitHub Context
        run: |
          echo "Repository:        ${{ github.repository }}"
          echo "Repository ID:     ${{ github.repository_id }}"
          echo "Repository URL:    ${{ github.repositoryUrl }}"
          echo "Server URL:        ${{ github.server_url }}"
          echo "API URL:           ${{ github.api_url }}"
          echo "GraphQL URL:       ${{ github.graphql_url }}"
          echo "Workflow:          ${{ github.workflow }}"
          echo "Ref:               ${{ github.ref }}"
          echo "Event Name:        ${{ github.event_name }}"
          echo "SHA:               ${{ github.sha }}"
          echo "Run ID:            ${{ github.run_id }}"
          echo "Run Number:        ${{ github.run_number }}"
          echo "Job:               ${{ github.job }}"
          echo "Actor:             ${{ github.actor }}"
          echo "Workspace:         ${{ github.workspace }}"
