name: Python Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python (uses actions/setup-python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'    # pick a specific version like '3.11' if you prefer
          
      # 3. Verify Python version (optional)
      - name: Print Python version
        run: python --version
