name: Secrets - UC 3

on:
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret (masked in logs)
        run: echo "secrets.MY_SECRET = ${{ secrets.MY_SECRET }}"
